name: CD

on:
  workflow_call:
    inputs:
      package_name:
        description: 'Package to deploy'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      AZURE_CREDENTIALS:
        description: 'Azure Credentials for AKS'
        required: true
jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      AWS_REGION: ${{ steps.set_vars.outputs.AWS_REGION }}
      AWS_S3_BUCKET: ${{ steps.set_vars.outputs.AWS_S3_BUCKET }}
      RESOURCE_GROUP: ${{ steps.set_vars.outputs.RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ steps.set_vars.outputs.AKS_CLUSTER_NAME }}
      PACKAGE_NAME: ${{ steps.set_vars.outputs.PACKAGE_NAME }}
    steps:
      - name: Set VARS
        id: set_vars
        run: |
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "AWS_S3_BUCKET=${{ vars.AWS_S3_BUCKET }}" >> $GITHUB_OUTPUT
          echo "RESOURCE_GROUP=${{ vars.RESOURCE_GROUP }}" >> $GITHUB_OUTPUT
          echo "AKS_CLUSTER_NAME=${{ vars.AKS_CLUSTER_NAME }}" >> $GITHUB_OUTPUT
          echo "PACKAGE_NAME=${{ inputs.package_name }}" >> $GITHUB_OUTPUT

  deploy:
    needs: set_vars
    uses: flavio185/ml-project-scaffold/.github/workflows/deploy-to-k8s.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    with:
      package_name: ${{ needs.set_vars.outputs.PACKAGE_NAME }}
      AWS_REGION: ${{ needs.set_vars.outputs.AWS_REGION }}
      AWS_S3_BUCKET: ${{ needs.set_vars.outputs.AWS_S3_BUCKET }}
      RESOURCE_GROUP: ${{ needs.set_vars.outputs.RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ needs.set_vars.outputs.AKS_CLUSTER_NAME }}

  create-and-publish-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ needs.set_vars.outputs.PACKAGE_NAME }}
          asset_name: ${{ needs.set_vars.outputs.PACKAGE_NAME }}
          asset_content_type: application/zip
