name: Create Scaffold Repository

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name'
        required: true
      author_name:
        description: 'Author name'
        required: true
      description:
        description: 'Project description'
        required: true
      python_version_number:
        description: 'Python version'
        required: true
        default: '3.10'

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scaffold repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Generate project from template
        run: |
          cookiecutter cookiecutter-templates --no-input \
            project_name="${{ github.event.inputs.project_name }}" \
            author_name="${{ github.event.inputs.author_name }}" \
            description="${{ github.event.inputs.description }}" \
            python_version_number="${{ github.event.inputs.python_version_number }}"

      - name: Set repository name
        run: |
          REPO_NAME=$(echo "${{ github.event.inputs.project_name }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV


      - name: Create repository
        env:
          GH_TOKEN: ${{ secrets.REPO_CREATOR_PAT }}
        run: | 
          gh auth status
          gh repo create "$REPO_NAME" --public --description "${{ github.event.inputs.description }}" \
          -y \
          --add-readme

      - name: Push scaffold to new repo
        run: |
          cd $REPO_NAME
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.REPO_CREATOR_PAT }}@github.com/${{ github.repository_owner }}/$REPO_NAME.git
          git add .
          git commit -m "Initial commit from scaffold"
          git branch -M main
          git push -u origin main