name: Create Scaffold Repository

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name'
        required: true
      author_name:
        description: 'Author name'
        required: true
      description:
        description: 'Project description'
        required: true
      python_version_number:
        description: 'Python version'
        required: true
        default: '3.10'


jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scaffold repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Generate project from template
        run: |
          cookiecutter cookiecutter-templates --no-input \
            project_name="${{ github.event.inputs.project_name }}" \
            author_name="${{ github.event.inputs.author_name }}" \
            description="${{ github.event.inputs.description }}" \
            python_version_number="${{ github.event.inputs.python_version_number }}"

      - name: Set repository name
        run: |
          REPO_NAME=$(echo "${{ github.event.inputs.project_name }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV


      - name: Create repository
        env:
          GH_TOKEN: ${{ secrets.REPO_CREATOR_PAT }}
        run: | 
          gh repo create "$REPO_NAME" --public --description "${{ github.event.inputs.description }}"
      
      - name: Push secrets
        env:
          GH_TOKEN: ${{ secrets.REPO_CREATOR_PAT }}
        run: |
          gh variable set AWS_REGION -b "${{ vars.AWS_REGION }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh variable set AWS_S3_BUCKET -b "${{ vars.AWS_S3_BUCKET }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh variable set RESOURCE_GROUP -b "${{ vars.RESOURCE_GROUP }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh variable set AKS_CLUSTER_NAME -b "${{ vars.AKS_CLUSTER_NAME }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh secret set AWS_ACCESS_KEY_ID -b "${{ secrets.AWS_ACCESS_KEY_ID }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh secret set AWS_SECRET_ACCESS_KEY -b "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --repo "${{ github.repository_owner }}/$REPO_NAME"
          gh secret set AZURE_CREDENTIALS -b "${{ secrets.AZURE_CREDENTIALS }}" --repo "${{ github.repository_owner }}/$REPO_NAME"

      - name: Push scaffold to new repo
        run: |
          cd $REPO_NAME
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@gmail.com"
          git remote add origin https://x-access-token:${{ secrets.REPO_CREATOR_PAT }}@github.com/${{ github.repository_owner }}/$REPO_NAME.git
          git add .
          git commit -m "Initial commit from scaffold"
          git branch -M main
          git push -u origin main
      
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

  summary:
    needs: generate-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Display Summary
        run: |
          echo "## Repository Creation Summary"
          echo ""
          echo "- Repository Name: "${{ github.repository_owner }}/$REPO_NAME}""
          echo "- Created by: ${{ github.actor }}"
          echo "- Description: ${{ github.event.inputs.description }}"
          echo ""
          echo "The repository has been created successfully with the initial scaffold."